### ISSUE TITLE
Nav Bar - Creation

### ISSUE THREAD

**Issue by Afilv222** [JasmailDuck/university-admission-tool#1]
Create a navigation bar that currently contains login, university page, program page, login and sign-up features. This will most likely be updated with more features if needed.

**Comment by Shreshthk1** [comment]
As a user, I want to be able to most access site pages from one place so that I can easily navigate throughout the site. This means Login, Signup

**Comment by JarHorner** [comment]
NavBar is created and has basic funtionallity. May need to add more links later.
